sonar.projectKey=naturacor3.0
sonar.sources=app,routes,resources
sonar.tests=tests
sonar.exclusions=vendor/**,node_modules/**,public/**,storage/**,bootstrap/**,tests/**
sonar.host.url=http://localhost:9000
sonar.token=sqp_ff1530fd666a293005cc96de9ab7cf69a93ebf10
sonar.php.version=8.2
sonar.sourceEncoding=UTF-8
sonar.php.coverage.reportPaths=coverage.xml