sonar.projectKey=75220834-cloud_PROYECTO-NATURACOR
sonar.organization=75220834-cloud
sonar.sources=app,routes,resources
sonar.tests=tests
sonar.exclusions=vendor/**,node_modules/**,public/**,storage/**,bootstrap/**
sonar.php.version=8.2
sonar.sourceEncoding=UTF-8
